version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: flower_user
      POSTGRES_PASSWORD: flower_pass
      POSTGRES_DB: flower_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init_full.sql:/docker-entrypoint-initdb.d/init.sql

  flowers_service:
    build: ./flowers_service
    container_name: flowers_service
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: flower_user
      DB_PASS: flower_pass
      DB_NAME: flower_db

volumes:
  pgdata:
